openapi: 3.1.0
info:
  version: 1.0.0
  title: Phonebook
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: Phone contacts manager
tags:
  - name: Contacts
    description: Operations with user's contacts book
  - name: Authentication
    description: Register, login, logout, refresh user operations

servers:
  - url: <https://nodejs-hw-mongodb-ntfc.onrender.com>
paths:
  /contacts:
    get:
      $ref: '../swagger/path/contacts/get.yaml'
    post:
      $ref: '../swagger/path/contacts/post.yaml'
  /contacts/:contactId:
    get:
      $ref: '../swagger/path/contacts/id/get.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
